apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort  # Change to LoadBalancer if using cloud provider
