services:
  broker:
    build:
      context: ./broker  # Path to Dockerfile for broker
    container_name: broker
    networks:
      my-network:
        aliases:
          - broker
    ports:
      - "8083:8083"

#    environment:
#      - ACTIVEMQ_HOST=server  # Use the alias defined above

  auldfellas:
    build:
      context: ./auldfellas  # Path to Dockerfile for auldfellas
    container_name: auldfellas
    networks:
      my-network:
        aliases:
          - auldfellas
#    depends_on:
#      - activemq  # Ensure auldfellas starts after activemq
#    environment:
#      - ACTIVEMQ_HOST=server  # Use the alias defined above

  dodgygeezers:
    build:
      context: ./dodgygeezers  # Path to Dockerfile for dodgygeezers
    container_name: dodgygeezers
    networks:
      my-network:
        aliases:
          - dodgygeezers
#    depends_on:
#      - activemq  # Ensure dodgygeezers starts after activemq
#    environment:
#      - ACTIVEMQ_HOST=server  # Use the alias defined above

  girlsallowed:
    build:
      context: ./girlsallowed  # Path to Dockerfile for girlsallowed
    container_name: girlsallowed
    networks:
      my-network:
        aliases:
          - girlsallowed
#    depends_on:
#      - activemq  # Ensure girlsallowed starts after activemq
#    environment:
#      - ACTIVEMQ_HOST=server  # Use the alias defined above

networks:
  my-network:
    driver: bridge
