apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodgygeezers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dodgygeezers
  template:
    metadata:
      labels:
        app: dodgygeezers
    spec:
      containers:
        - name: dodgygeezers
          image: dodgygeezers:latest  # or your-dockerhub-username/auldfellas:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          resources: # <--- Add this block
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"