apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'auldfellas'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['auldfellas:8080']
