apiVersion: v1
kind: Service
metadata:
  name: girlsallowed
spec:
  selector:
    app: girlsallowed
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  # type: ClusterIP is the default, so you can omit it
